server:
  port: 8100

spring:
  application:
    name: main
  redis:
    host: localhost
    port: 6379
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/ORCLCDB
    username: memories
    password: memories
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.Oracle12cDialect


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    fetch-registry: true
    register-with-eureka: true


#Logging
logging:
  level:
    root: info


